### ISSUE TITLE
삭제처리 에러 

### ISSUE THREAD

**Issue by m-pyo** [lifeisegg123/musical_review#18]
1페이지 이외의 페이지를 표시한 상태에서 삭제를 하는경우 
표시 페이지에서 1페이지의 정보를 취득하여 표시
![image](https://user-images.githubusercontent.com/58651261/99685788-4d144f80-2ac6-11eb-9271-1919945558bc.png)

**Comment by lifeisegg123** [comment]
리덕스 쪽 파라미터 문제, 해결완료.
