### ISSUE TITLE
사진 표시에러 수정요청

### ISSUE THREAD

**Issue by m-pyo** [lifeisegg123/musical_review#19]
![image](https://user-images.githubusercontent.com/58651261/99827844-81a70a80-2b9d-11eb-9ea5-54c98cb5bcf3.png)

base64 형식의 이미지 앞에 localhost:5000/이 붙어 표시되어 이미지가 깨진상태로 표시 
base64형식과 경로로 전달받는 경우의 조건분기 필요

**Comment by lifeisegg123** [comment]
해결완료
